title: CheatSheets.zip
subtitle: Ultimate Cheat for Developers
description: Share quick reference and cheat sheet for developers
keywords: >-
  cheat,sheet,cheatsheets,reference,programming,code
  table,snippets,linux,command,shortcuts,developers
author: Fechin
language: en
timezone: UTC
url: https://maksimzinovev.github.io/reference
root: /reference/
permalink: ":name.html"
permalink_defaults: null
pretty_urls:
  trailing_index: false
  trailing_html: true
source_dir: source
public_dir: public
archive_dir: archives
i18n_dir: ":lang"
skip_render:
  - assets/**/*
new_post_name: ":title.md"
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ""
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: null
highlight:
  enable: false
index_generator:
  path: ""
  per_page: 0
  order_by: "-date"
default_category: uncategorized
category_map: {}
tag_map: {}
meta_generator: false
seo:
  default_image: /assets/image/preview.png
  author_name: Fechin
  author_url: https://cheatsheets.zip
  social:
    twitter: Fechin
    github: Fechin/reference
  site_type: Educational Technology Platform
  target_audience: Developers, Programmers, System Administrators
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: date
per_page: 10
pagination_dir: page
include: []
exclude:
  - .github
ignore: []
theme: coo
nofollow:
  enable: true
  field: site
  exclude:
    - tableconvert.com
    - dorefer.com
    - fionaai.com
    - github.com
    - x.com
excerpt:
  depth: 2
  excerpt_excludes: []
  more_excludes: []
  hideWholePostExcerpts: true
deploy:
  - type: git
    repo: https://github.com/MaksimZinovev/reference.git
    branch: gh-pages
server:
  compress: true
sitemap:
  path: sitemap.xml
  tags: false
  categories: false
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: false
    typographer: false
    quotes: “”‘’
    langPrefix: hljs language-
  anchors:
    level: 2
    collisionSuffix: ""
    permalink: true
    permalinkClass: h-anchor
    permalinkSymbol: "#"
    case: 1
    separator: "-"
browsersync:
  ui: false
  notify: false
  logLevel: silent
